### PR TITLE
Refactor shim so that it can be called without url parameters

### PR DESCRIPTION
**Pull request by lamplightdev**
Addresses #6

### CODE REVIEW

**Comment by lamplightdev** [comment]
Yep, I see how to remove `global` now :)

I can have a go at updating the docs if you like - how would you suggest referring more generally to `deno` and `node` contexts?

**Comment by matthewp** [comment]
I would probably want to avoid talking about `node`, as I don't want to *officially* support it. Doing so would mean, I think, having an npm package which I definitively not want. I do want this library to be runtime agnostic pure JavaScript, however, so anyone willing to bundle should be able to run it almost anywhere that supports the JS features.

But we can definitely document this new entry point. I think I'm going to refactor to be a class so I can add docs when I do that.

**Comment by matthewp** [comment]
Merged as is, looks good! I'll release after making this into a class and documenting, probably tomorrow morning, thanks again!

**Comment by lamplightdev** [comment]
Cheers!

**Comment by matthewp** [comment]
Still working on the refactor, have gone back and forth a little bit between a class and a global singleton function, but now I think I have figured out a better way to make it a class.

**Pull request merged**
